a =["FCT", ["Gwagwalada", "Kuje", "Abaji","Abuja Municipal","Bwari","Kwali", "Others"], ['ABIA', ["Aba North","Aba South","Arochukwu","Bende","Ikwuano","Isiala Ngwa North","Isiala Ngwa South","Isuikwuato","Obi Ngwa","Ohafia","Ohafia","Ugwunagbo","Ukwa East","Ukwa West","Umuahia North","Umuahia South","Umu Nneochi"],
    ['ADAMAWA',  ["Demsa","Fufore","Ganye","Gayuk","Gombi","Hong","Jada","Lamurde","Madagali","Mayo Belwa","Michika","Mubi North","Mubi South","Numan","Shelleng","Song","Toungo","Yola North","Yola South"],
    ['AKWAIBOM' , ["Abak","Eastern Obolo","Eket","Esit Eket","Essien Udim","Etim Ekpo","Etinan","Ibeno","Ibesikpo Asutan","Ibiono-Ibom","Ika","Ikono","Ikot Abasi","Ikot Ekpene","Ini","Itu","Mbo","Mkpat-Enin","Nsit-Atai","Nsit-Ibom","Nsit-Ubium","Obot Akara","Okobo","Onna","Oron","Oruk Anam","Udung-Uko","Ukanafun","Uruan","Urue-Offong\/Oruko","Uyo"],
    ['ANAMBRA' , ["Aguata","Anambra East","Anambra West","Anaocha","Awka North","Awka South","Ayamelum","Dunukofia","Ekwusigo","Idemili North","Idemili South","Ihiala","Njikoka","Nnewi North","Nnewi South","Ogbaru","Onitsha North","Onitsha South","Orumba North","Orumba South","Oyi"],
    ['BAUCHI' , ["Alkaleri","Bauchi","Bogoro","Damban","Darazo","Dass","Gamawa","Ganjuwa","Giade","Itas Gadau","Jama'are","Katagum","Kirfi","Misau","Ningi","Shira","Tafawa Balewa","Toro","Warji","Zaki"],
    ['BAYELSA' , ["Brass","Ekeremor","Kolokuma Opokuma","Nembe","Ogbia","Sagbama","Southern Ijaw","Yenagoa"],
    ['BENUE' , ["Apa","Ado","Agatu","Buruku","Gboko","Guma","Gwer East","Gwer West","Katsina-Ala","Konshisha","Kwande","Logo","Makurdi","Obi","Ogbadibo","Ohimini","Oju","Okpokwu","Oturkpo","Tarka","Ukum","Ushongo","Vandeikya"],
    ['BORNO' , ["Abadam","Askira/Uba","Bama","Bayo","Biu","Chibok","Damboa","Dikwa","Gubio","Guzamala","Gwoza","Hawul","Jere","Kaga","Kala/Balge","Konduga","Kukawa","Kwaya Kusar","Mafa","Magumeri","Maiduguri","Marte","Mobbar","Monguno","Ngala","Nganzai","Shani"],
    ['CROSSRIVER' ,["Akamkpa","Akpabuyo","Bakassi","Bekwarra","Biase","Boki","Calabar Municipal","Calabar South","Etung","Ikom","Obanliku","Obubra","Obudu","Odukpani","Ogoja","Yakuur","Yala"],
    ['DELTA' , ["Aniocha South","Bomadi","Burutu","Ethiope East","Ethiope West","Ika North East","Ika South","Isoko North","Isoko South","Ndokwa East","Ndokwa West","Okpe","Oshimili North","Oshimili South","Patani","Sapele","Udu","Ughelli North","Ughelli South","Ukwuani","Uvwie","Warri North","Warri South","Warri South West"],
    ['EBONYI' , ["Afikpo North","Afikpo South","Ebonyi","Ezza North","Ezza South","Ikwo","Ishielu","Ivo","Izzi","Ohaozara","Ohaukwu","Onicha"],
    ['EDO' , ["Egor","Esan Central","Esan North-East","Esan South-East","Esan West","Etsako Central","Etsako East","Etsako West","Igueben","Ikpoba Okha","Orhionmwon","Oredo","Ovia North-East","Ovia South-West","Owan East","Owan West","Uhunmwonde"],
    ['EKITI' , ["Ado","Efon","Ekiti East","Ekiti South-West","Ekiti West","Emure","Gbonyin","Ido/Osi","Ijero","Ikere","Ikole","Ilejemeje","Irepodun/Ifelodun","Ise\/Orun","Moba","Oye"],
    ['ENUGU' , ["Awgu","Enugu East","Enugu North","Enugu South","Ezeagu","Igbo Etiti","Igbo Eze North","Igbo Eze South","Isi Uzo","Nkanu East","Nkanu West","Nsukka","Oji River","Udenu","Udi","Uzo Uwani"],
    ['GOMBE' , ["Akko","Balanga","Billiri","Dukku","Funakaye","Gombe","Kaltungo","Kwami","Nafada","Shongom","Yamaltu/Deba"],
    ['IMO' , ["Aboh-Mbaise","Ahiazu Mbaise","Ehime Mbano","Ezinihitte","Ideato North","Ideato South","Ihitte/Uboma","Ikeduru","Isiala Mbano","Isu","Mbaitoli","Ngor Okpala","Njaba","Nkwerre","Nwangele","Obowo","Oguta","Ohaji\/Egbema","Okigwe","Orlu","Orsu","Oru East","Oru West","Owerri Municipal","Owerri North","Owerri West","Unuimo"],
    ['JIGAWA' , ["Auyo","Babura","Biriniwa","Birnin Kudu","Buji","Dutse","Gagarawa","Garki","Gumel","Guri","Gwaram","Gwiwa","Hadejia","Jahun","Kafin Hausa","Kazaure","Kiri Kasama","Kiyawa","Kaugama","Maigatari","Malam Madori","Miga","Ringim","Roni","Sule Tankarkar","Taura","Yankwashi"],
    ['KADUNA' , ["Birni-Gwari","Chikun","Giwa","Igabi","Ikara","Jaba","Jemaa","Kachia","Kaduna North","Kaduna South","Kagarko","Kajuru","Kaura","Kauru","Kubau","Kudan","Lere","Makarfi","Sabon Gari","Sanga","Soba","Zangon Kataf","Zaria"],
    ['KANO' , ["Ajingi","Albasu","Bagwai","Bebeji","Bichi","Bunkure","Dala","Dambatta","Dawakin Kudu","Dawakin Tofa","Doguwa","Fagge","Gabasawa","Garko","Garun Mallam","Gaya","Gezawa","Gwale","Gwarzo","Kabo","Kano Municipal","Karaye","Kibiya","Kiru","Kumbotso","Kunchi","Kura","Madobi","Makoda","Minjibir","Nasarawa","Rano","Rimin Gado","Rogo","Shanono","Sumaila","Takai","Tarauni","Tofa","Tsanyawa","Tudun Wada","Ungogo","Warawa","Wudil"],
    ['KATSINA' , ["Bakori","Batagarawa","Batsari","Baure","Bindawa","Charanchi","Dandume","Danja","Dan Musa","Daura","Dutsi","Dutsin Ma","Faskari","Funtua","Ingawa","Jibia","Kafur","Kaita","Kankara","Kankia","Katsina","Kurfi","Kusada","Mai'Adua","Malumfashi","Mani","Mashi","Matazu","Musawa","Rimi","Sabuwa","Safana","Sandamu","Zango"],
    ['KEBBI' , ["Aleiro","Arewa Dandi","Argungu","Augie","Bagudo","Birnin Kebbi","Bunza","Dandi","Fakai","Gwandu","Jega","Kalgo","Koko\/Besse","Maiyama","Ngaski","Sakaba","Shanga","Suru","Wasagu\/Danko","Yauri","Zuru"],
    ['KOGI' , ["Adavi","Ajaokuta","Ankpa","Bassa","Dekina","Ibaji","Idah","Igalamela Odolu","Ijumu","Kabba/Bunu","Kogi","Lokoja","Mopa Muro","Ofu","Ogori Magongo","Okehi","Okene","Olamaboro","Omala","Yagba East","Yagba West"],
    ['KWARA' , ["Asa","Baruten","Edu","Ekiti","Ifelodun","Ilorin East","Ilorin South","Ilorin West","Irepodun","Isin","Kaiama","Moro","Offa","Oke Ero","Oyun","Pategi"],
    ['LAGOS' , ["Agege","Ajeromi-Ifelodun","Alimosho","Amuwo-Odofin","Apapa","Badagry","Epe","Eti Osa","Ibeju-Lekki","Ifako-Ijaiye","Ikeja","Ikorodu","Kosofe","Lagos Island","Lagos Mainland","Mushin","Ojo","Oshodi-Isolo","Shomolu","Surulere"],
    ['NASARAWA' ,["Akwanga","Awe","Doma","Karu","Keana","Keffi","Kokona","Lafia","Nasarawa","Nasarawa Egon","Obi","Toto","Wamba"],
    ['NIGER' , ["Agaje","Agwara","Bida","Borgu","Bosso","Chanchaga","Edati","Gbako","Gurara","Katcha","Kontagora","Lapai","Lavun","Magama","Mariga","Mashegu","Mokwa","Moya","Paikoro","Rafi","Rijau","Shiroro","Suleja","Tafa","Wushishi"],
    ['OGUN' , ["Abeokuta North","Abeokuta South","Ado-Odo\/Ota","Egbado North","Egbado South","Ewekoro","Ifo","Ijebu East","Ijebu North","Ijebu North East","Ijebu Ode","Ikenne","Imeko Afon","Ipokia","Obafemi Owode","Odeda","Odogbolu","Ogun Waterside","Remo North","Shagamu"],
    ['ONDO' , ["Akoko North-East","Akoko North-West","Akoko South-West","Akoko South-East","Akure North","Akure South","Ese Odo","Idanre","Ifedore","Ilaje","Ile Oluji\/Okeigbo","Irele","Odigbo","Okitipupa","Ondo East","Ondo West","Ose","Owo"],
    ['OSUN' , ["Aiyedade","Aiyedire","Atakumosa East","Atakumosa West","Boluwaduro","Boripe","Ede North","Ede South","Egbedore","Ejigbo","Ife Central","Ife East","Ife North","Ife South","Ifedayo","Ifelodun","Ila","Ilesha East", "Ilesha West", "Irepodun","Irewole","Isokan","Iwo","Obokun","Odo-Otin","Ola-Oluwa","Olarunda","Oriade","Orolu","Osogbo"],
    ['OYO' , ["Afijio","Akinyele","Atiba","Atisbo","Egbeda","Ibadan North","Ibadan North-East","Ibadan North-West","Ibadan South-East","Ibadan South-West","Ibarapa Central","Ibarapa East","Ibarapa North","Ido","Irepo","Iseyin","Itesiwaju","Iwajowa","Kajola","Lagelu","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Olorunsogo","Oluyole","Ona Ara","Orelope","Ori Ire","Oyo","Oyo East","Saki East","Saki West","Surulere"],
    ['PLATEAU' ,["Barkin Ladi","Bassa","Jos East","Jos North","Jos South","Kanam","Kanke","Langtang South","Langtang North","Mangu","Mikang","Pankshin","Qua'an Pan","Riyom","Shendam","Wase"],
    ['RIVERS' ,["Abua/Odual","Ahoada East","Ahoada West","Akuku-Toru","Andoni","Asari-Toru","Bonny","Degema","Eleme","Emuoha","Etche","Gokana","Ikwerre","Khana","Obio\/Akpor","Ogba\/Egbema\/Ndoni","Ogu\/Bolo","Okrika","Omuma","Opobo\/Nkoro","Oyigbo","Port Harcourt","Tai"],
    ['SOKOTO' ,["Binji","Bodinga","Dange Shuni","Gada","Goronyo","Gudu","Gwadabawa","Illela","Isa","Kebbe","Kware","Rabah","Sabon Birni","Shagari","Silame","Sokoto North","Sokoto South","Tambuwal","Tangaza","Tureta","Wamako","Wurno","Yabo"],
    ['TARABA' ,["Ardo-kola","Bali","Donga","Gashaka","Gassol","Ibi","Jalingo","Karim Lamido","Kumi","Lau","Sardauna","Takum","Ussa","Wukari","Yorro","Zing"],
    ['YOBE' ,["Bade","Bursari","Damaturu","Fika","Fune","Geidam","Gujba","Gulani","Jakusko","Karasuwa","Machina","Nangere","Nguru","Potiskum","Tarmuwa","Yunusari","Yusufari"],
    ['ZAMFARA' ,["Bakura","Birnin Magaji Kiyaw","Bukkuyum","Bungudu","Gummi","Gusau","Kaura Namoda","Maradun","Maru","Shinkafi","Talata Mafara","Tsafe","Zurmi"]

]

s = collections.OrderedDict(a)
for ny , ret in s.items():
    print(ny)
    print(ret)

for all, any in s.items():
    state = State(name=all)
    state.save()
    for local in any:
        lg = LocalGovernment(name=local, country=state)
        lg.save()

a ={'FCT': ["Gwagwalada", "Kuje", "Abaji","Abuja Municipal","Bwari","Kwali", "Others"], 'ABIA': ["Aba North","Aba South","Arochukwu","Bende","Ikwuano","Isiala Ngwa North","Isiala Ngwa South","Isuikwuato","Obi Ngwa","Ohafia","Ohafia","Ugwunagbo","Ukwa East","Ukwa West","Umuahia North","Umuahia South","Umu Nneochi"],
    'ADAMAWA' : ["Demsa","Fufore","Ganye","Gayuk","Gombi","Hong","Jada","Lamurde","Madagali","Mayo Belwa","Michika","Mubi North","Mubi South","Numan","Shelleng","Song","Toungo","Yola North","Yola South"],
    'AKWAIBOM' : ["Abak","Eastern Obolo","Eket","Esit Eket","Essien Udim","Etim Ekpo","Etinan","Ibeno","Ibesikpo Asutan","Ibiono-Ibom","Ika","Ikono","Ikot Abasi","Ikot Ekpene","Ini","Itu","Mbo","Mkpat-Enin","Nsit-Atai","Nsit-Ibom","Nsit-Ubium","Obot Akara","Okobo","Onna","Oron","Oruk Anam","Udung-Uko","Ukanafun","Uruan","Urue-Offong\/Oruko","Uyo"],
    'ANAMBRA' : ["Aguata","Anambra East","Anambra West","Anaocha","Awka North","Awka South","Ayamelum","Dunukofia","Ekwusigo","Idemili North","Idemili South","Ihiala","Njikoka","Nnewi North","Nnewi South","Ogbaru","Onitsha North","Onitsha South","Orumba North","Orumba South","Oyi"],
    'BAUCHI' : ["Alkaleri","Bauchi","Bogoro","Damban","Darazo","Dass","Gamawa","Ganjuwa","Giade","Itas\/Gadau","Jama'are","Katagum","Kirfi","Misau","Ningi","Shira","Tafawa Balewa","Toro","Warji","Zaki"],
    'BAYELSA' : ["Brass","Ekeremor","Kolokuma\/Opokuma","Nembe","Ogbia","Sagbama","Southern Ijaw","Yenagoa"],
    'BENUE' : ["Apa","Ado","Agatu","Buruku","Gboko","Guma","Gwer East","Gwer West","Katsina-Ala","Konshisha","Kwande","Logo","Makurdi","Obi","Ogbadibo","Ohimini","Oju","Okpokwu","Oturkpo","Tarka","Ukum","Ushongo","Vandeikya"],
    'BORNO' : ["Abadam","Askira/Uba","Bama","Bayo","Biu","Chibok","Damboa","Dikwa","Gubio","Guzamala","Gwoza","Hawul","Jere","Kaga","Kala/Balge","Konduga","Kukawa","Kwaya Kusar","Mafa","Magumeri","Maiduguri","Marte","Mobbar","Monguno","Ngala","Nganzai","Shani"],
    'CROSSRIVER' :["Akamkpa","Akpabuyo","Bakassi","Bekwarra","Biase","Boki","Calabar Municipal","Calabar South","Etung","Ikom","Obanliku","Obubra","Obudu","Odukpani","Ogoja","Yakuur","Yala"],
    'DELTA' : ["Aniocha South","Bomadi","Burutu","Ethiope East","Ethiope West","Ika North East","Ika South","Isoko North","Isoko South","Ndokwa East","Ndokwa West","Okpe","Oshimili North","Oshimili South","Patani","Sapele","Udu","Ughelli North","Ughelli South","Ukwuani","Uvwie","Warri North","Warri South","Warri South West"],
    'EBONYI' : ["Afikpo North","Afikpo South","Ebonyi","Ezza North","Ezza South","Ikwo","Ishielu","Ivo","Izzi","Ohaozara","Ohaukwu","Onicha"],
    'EDO' : ["Egor","Esan Central","Esan North-East","Esan South-East","Esan West","Etsako Central","Etsako East","Etsako West","Igueben","Ikpoba Okha","Orhionmwon","Oredo","Ovia North-East","Ovia South-West","Owan East","Owan West","Uhunmwonde"],
    'EKITI' : ["Ado","Efon","Ekiti East","Ekiti South-West","Ekiti West","Emure","Gbonyin","Ido/Osi","Ijero","Ikere","Ikole","Ilejemeje","Irepodun/Ifelodun","Ise\/Orun","Moba","Oye"],
    'ENUGU' : ["Awgu","Enugu East","Enugu North","Enugu South","Ezeagu","Igbo Etiti","Igbo Eze North","Igbo Eze South","Isi Uzo","Nkanu East","Nkanu West","Nsukka","Oji River","Udenu","Udi","Uzo Uwani"],
    'GOMBE' : ["Akko","Balanga","Billiri","Dukku","Funakaye","Gombe","Kaltungo","Kwami","Nafada","Shongom","Yamaltu/Deba"],
    'IMO' : ["Aboh-Mbaise","Ahiazu Mbaise","Ehime Mbano","Ezinihitte","Ideato North","Ideato South","Ihitte/Uboma","Ikeduru","Isiala Mbano","Isu","Mbaitoli","Ngor Okpala","Njaba","Nkwerre","Nwangele","Obowo","Oguta","Ohaji\/Egbema","Okigwe","Orlu","Orsu","Oru East","Oru West","Owerri Municipal","Owerri North","Owerri West","Unuimo"],
    'JIGAWA' : ["Auyo","Babura","Biriniwa","Birnin Kudu","Buji","Dutse","Gagarawa","Garki","Gumel","Guri","Gwaram","Gwiwa","Hadejia","Jahun","Kafin Hausa","Kazaure","Kiri Kasama","Kiyawa","Kaugama","Maigatari","Malam Madori","Miga","Ringim","Roni","Sule Tankarkar","Taura","Yankwashi"],
    'KADUNA' : ["Birni-Gwari","Chikun","Giwa","Igabi","Ikara","Jaba","Jemaa","Kachia","Kaduna North","Kaduna South","Kagarko","Kajuru","Kaura","Kauru","Kubau","Kudan","Lere","Makarfi","Sabon Gari","Sanga","Soba","Zangon Kataf","Zaria"],
    'KANO' : ["Ajingi","Albasu","Bagwai","Bebeji","Bichi","Bunkure","Dala","Dambatta","Dawakin Kudu","Dawakin Tofa","Doguwa","Fagge","Gabasawa","Garko","Garun Mallam","Gaya","Gezawa","Gwale","Gwarzo","Kabo","Kano Municipal","Karaye","Kibiya","Kiru","Kumbotso","Kunchi","Kura","Madobi","Makoda","Minjibir","Nasarawa","Rano","Rimin Gado","Rogo","Shanono","Sumaila","Takai","Tarauni","Tofa","Tsanyawa","Tudun Wada","Ungogo","Warawa","Wudil"],
    'KATSINA' : ["Bakori","Batagarawa","Batsari","Baure","Bindawa","Charanchi","Dandume","Danja","Dan Musa","Daura","Dutsi","Dutsin Ma","Faskari","Funtua","Ingawa","Jibia","Kafur","Kaita","Kankara","Kankia","Katsina","Kurfi","Kusada","Mai'Adua","Malumfashi","Mani","Mashi","Matazu","Musawa","Rimi","Sabuwa","Safana","Sandamu","Zango"],
    'KEBBI' : ["Aleiro","Arewa Dandi","Argungu","Augie","Bagudo","Birnin Kebbi","Bunza","Dandi","Fakai","Gwandu","Jega","Kalgo","Koko\/Besse","Maiyama","Ngaski","Sakaba","Shanga","Suru","Wasagu\/Danko","Yauri","Zuru"],
    'KOGI' : ["Adavi","Ajaokuta","Ankpa","Bassa","Dekina","Ibaji","Idah","Igalamela Odolu","Ijumu","Kabba/Bunu","Kogi","Lokoja","Mopa Muro","Ofu","Ogori\/Magongo","Okehi","Okene","Olamaboro","Omala","Yagba East","Yagba West"],
    'KWARA' : ["Asa","Baruten","Edu","Ekiti","Ifelodun","Ilorin East","Ilorin South","Ilorin West","Irepodun","Isin","Kaiama","Moro","Offa","Oke Ero","Oyun","Pategi"],
    'LAGOS' : ["Agege","Ajeromi-Ifelodun","Alimosho","Amuwo-Odofin","Apapa","Badagry","Epe","Eti Osa","Ibeju-Lekki","Ifako-Ijaiye","Ikeja","Ikorodu","Kosofe","Lagos Island","Lagos Mainland","Mushin","Ojo","Oshodi-Isolo","Shomolu","Surulere"],
    'NASARAWA' :["Akwanga","Awe","Doma","Karu","Keana","Keffi","Kokona","Lafia","Nasarawa","Nasarawa Egon","Obi","Toto","Wamba"],
    'NIGER' : ["Agaje","Agwara","Bida","Borgu","Bosso","Chanchaga","Edati","Gbako","Gurara","Katcha","Kontagora","Lapai","Lavun","Magama","Mariga","Mashegu","Mokwa","Moya","Paikoro","Rafi","Rijau","Shiroro","Suleja","Tafa","Wushishi"],
    'OGUN' : ["Abeokuta North","Abeokuta South","Ado-Odo\/Ota","Egbado North","Egbado South","Ewekoro","Ifo","Ijebu East","Ijebu North","Ijebu North East","Ijebu Ode","Ikenne","Imeko Afon","Ipokia","Obafemi Owode","Odeda","Odogbolu","Ogun Waterside","Remo North","Shagamu"],
    'ONDO' : ["Akoko North-East","Akoko North-West","Akoko South-West","Akoko South-East","Akure North","Akure South","Ese Odo","Idanre","Ifedore","Ilaje","Ile Oluji\/Okeigbo","Irele","Odigbo","Okitipupa","Ondo East","Ondo West","Ose","Owo"],
    'OSUN' : ["Aiyedade","Aiyedire","Atakumosa East","Atakumosa West","Boluwaduro","Boripe","Ede North","Ede South","Egbedore","Ejigbo","Ife Central","Ife East","Ife North","Ife South","Ifedayo","Ifelodun","Ila","Ilesha East", "Ilesha West", "Irepodun","Irewole","Isokan","Iwo","Obokun","Odo-Otin","Ola-Oluwa","Olarunda","Oriade","Orolu","Osogbo"],
    'OYO' : ["Afijio","Akinyele","Atiba","Atisbo","Egbeda","Ibadan North","Ibadan North-East","Ibadan North-West","Ibadan South-East","Ibadan South-West","Ibarapa Central","Ibarapa East","Ibarapa North","Ido","Irepo","Iseyin","Itesiwaju","Iwajowa","Kajola","Lagelu","Ogbomosho North","Ogbomosho South","Ogo Oluwa","Olorunsogo","Oluyole","Ona Ara","Orelope","Ori Ire","Oyo","Oyo East","Saki East","Saki West","Surulere"],
    'PLATEAU' :["Barkin Ladi","Bassa","Bokkos""Jos East","Jos North","Jos South","Kanam","Kanke","Langtang South","Langtang North","Mangu","Mikang","Pankshin","Qua'an Pan","Riyom","Shendam","Wase"],
    'RIVERS' :["Abua/Odual","Ahoada East","Ahoada West","Akuku-Toru","Andoni","Asari-Toru","Bonny","Degema","Eleme","Emuoha","Etche","Gokana","Ikwerre","Khana","Obio\/Akpor","Ogba\/Egbema\/Ndoni","Ogu\/Bolo","Okrika","Omuma","Opobo\/Nkoro","Oyigbo","Port Harcourt","Tai"],
    'SOKOTO' :["Binji","Bodinga","Dange Shuni","Gada","Goronyo","Gudu","Gwadabawa","Illela","Isa","Kebbe","Kware","Rabah","Sabon Birni","Shagari","Silame","Sokoto North","Sokoto South","Tambuwal","Tangaza","Tureta","Wamako","Wurno","Yabo"],
    'TARABA' :["Ardo-kola","Bali","Donga","Gashaka","Gassol","Ibi","Jalingo","Karim Lamido","Kumi","Lau","Sardauna","Takum","Ussa","Wukari","Yorro","Zing"],
    'YOBE' :["Bade","Bursari","Damaturu","Fika","Fune","Geidam","Gujba","Gulani","Jakusko","Karasuwa","Machina","Nangere","Nguru","Potiskum","Tarmuwa","Yunusari","Yusufari"],
    'ZAMFARA' :["Bakura","Birnin Magaji\/Kiyaw","Bukkuyum","Bungudu","Gummi","Gusau","Kaura Namoda","Maradun","Maru","Shinkafi","Talata Mafara","Tsafe","Zurmi"]

    }

pool_data = { 'ABBA NA SHEHU':[ "NO. 82/I BAUCHI ROAD (BAUCHI ROAD I) 001",
"NO. I07/I ALONG BAUCHI ROAD (BAUCHI ROAD II) 002", "NO 64/II TURAKI LANE (YANDOKA TURAKI I) 003",
"NO 84/5 YANDOKA TURAKI LANE (YAN DOKA TURAKI) 004", "NO. II6/I6 LAWAN NA ROGO (LAWAN NA ROGO) 005",
"NO 85/I4 YANDOKA/TURAKI (SCHOOL LANE I) 006", "NO. III/9 SCHOOL LANE (SCHOOL LANE II) 007",
"NO. I/74/35 AUDU KENKEN (AUDU KENKEN) 008", "NO. 68/27 MAMMAN BORNO STREET (MAMMAN BORNO I) 009",
"NO. II3/30 ALONG BUZU STREET (MAMMAN BORNO II) 010", "NO. I25/I ABBA NA SHEHU STREET (ABBA SHEHU NA I) 011",
"NO. I28/9 ABBA NA SHEHU STREET (ABBA SHEHU NA II) 012", "NO. I3I/3 ABBA NA SHEHU (ABBA SHEHU NA III) 013",
"NO. I32/I GARBA JIBIYA (KOFAR SARKIN KUBI) 014", "NO. I25/II GARBA JIBIYA STREET (GARBA JIBIYA) 015",
"NO. I34/4 IDI MAI BORKONO ABBA NA (IDI MAI BORKONO) 016" ,"OPPOSITE CENTRAL MOSQUE JOS (MASS JUMMA’A STREET) 017",
"AUDU LANE JUNCTION (AUDU LANE) 018", "NO. 84/I7 TURAKI LANE (TURAKI LANE) 019",
"NO. 86/I MANGO STREET (MANGO STREET) 020", "NO. I29/9 YAN REKE (YAN REKE) 021",
"NO. I42/3 INUWA KANO STREET (INUWA KANO) 022", "NO. 57/2 BEHIND JOS NORTH LGC SHOPPING COMPLEX (BAKANO LANE) 023",
"NO. I2I/I3 SCHOOL LANE (SCHOOL LANE) 024", "MATANMI HOSPITAL AND MATERNITY JOS (MAMMAN BORNO) 025",
"NO. I28/I AUDU KENKEN STREET (MASSALACI JUMMA'A STREET I) 026", "NO. I28/2 AUDU KENKEN STREET (AUDU KENKEN) 027",
"NO. I22/2 ALONG BAUCHI ROAD (BAUCHI ROAD) 028","OPPOSITE CENTRAL MOSQUE JOS (MASSALACI JUMMA'A STREET II) 029"],

              'ALI KAZAURE':["ABDULSALAMI ST. I001","NEW MARKET 002","NEAR THE CLAN HEAD’S COMPOUND I (KOFAR MAI UNGUWA I) 003",
                "NEAR THE CLAN HEAD’S COMPOUND II (KOFAR MAI UNGUWA II) 004","ALH. UMAR LANE I005","ALH. UMAR LANE II 006",
                "SARKI MANGU STREET 007","LAMBERT STREET 008","UNG. DALYOP JUNCTION I009","IDI MAI BORKONO 010",
                "EMENIKE STREET 011","UNG. DALYOP JUNCTION II 012","HARUNA HADEJA 013","LASISI MAKANJUOLA 014","AMINGO JUNCTION I015",
                "NEAR MASSALLACI IDI (KOFAR MAI UNGUWA) 016","MONEDO STREET 017","ALI KAZAURE 018","LGED SCHOOL 019",
                "MALLAM KURE ST. 020","ASIBITIN KUTARE 021","MOSES ANYANSI ST. 022","NEW MARKET 023","COMMUNITY CENTRE 024","HALIRU STREET 025","ABDULSALAMI ST. II 026","ISHAKU GWAMNA ST. 027",
                "NEAR MUDI NA GARBA STREET (KOFAR YAHAI MAITAYA) 028","FED. HOTEL JUNCTION 029","COMMUNITY CENTRE 030",
                "RELEVANT TECH 031","NURUDEEN TOWNSHIP SCH. 032","MUDI NA GARBA 033","YAN KAJI 034",
                "ALI KAZAURE ST. 035","OSUMENYI STREET 036","NEW MARKET 037","AMINGO JUNCTION II 038"],
              'GARBA DAHO':["SARKI STREET 001",
"GALADIMA STREET 002",
"ALH. FADI STREET I003",
"COLE STREET 004",
"PUMP STREET 005",
"BAUCHI ROAD 006",
"NDU STREET 007",
"KASUWA DARE I 008",
"KASUWA DARE II 009",
"AYENI STREET I 010",
"AYENI STREET II 011",
"BUTCHER LANE 012",
"SANI STREET 013",
"YAN TAYA 014",
"YAN TINKA 015",
"MEGA STREET 016",
"YAN DOYA 017",
"KASUWA DARE JUNCTION 018",
"SARKI STREET 019",
"YAN TAYA JUNCTION 020"
"GALADIMA ST. JUNCTION 021",
"DILIMI STREET (BEHIND CARDINAL ROAD) 022",
"ALH. FADI STREET II 023",
"COLE STREET JUNCTION 024",
"MASSALACI DILIMI STREET 025",
"YAN KATIFA DILIMI 026"],
                'GANGARE':["LGED GANGARE 001",
"GSS GANGARE 002",
"ADJACENT ALHAJI MAISAJE’S HOUSE, GANGARE I (KOFAR MAISAJE I) 003",
"ADJACENT ALHAJI MAISAJE’S HOUSE, GANGARE II (KOFAR MAISAJE II) 004",
"PARENTIN ITACHE 005",
"K/ALH. GAMBO 006",
"YAN KASHI I 007",
"YAN KASHI II 008",
"K/MAL. MUSA 009",
"RICHARD WAY 010",
"POST OFFICE 011",
"RAILWAY STATION 012",
"NO. 56 MURTALA MOHAMMED WAY (MURTALA WAY) 013",
"ADJACENT ALHAJI MAGAJI HOUSE GANGARE (KOFAR MAGAJI) 014",
"ADJACENT ALHAJI SALEH HASSAN’S HOUSE GANGARE (DAKIN MINTI) 015",
"ADJACENT SARKIN DOGARIA’S HOUSE GANGARE (K/SARKIN DOGARAI) 016",
"ADJACENT SHEHU SALEH HASSAN’S COMPOUND (KOFAR SHEHU) 017",
"KOFAR YAYA 018",
"KOFAR KATAGUM 019",
"GSS GANGARE 020"],
              'IBRAHIM KATSINA':["NO 32 ADEBAYO STREET (ADEBAYO STREET) 001",
"NO 36/IA KOLO STREET (KOLO STREET) 002",
"NO. 29/6 BAUCHI ROAD (BAUCHI ROAD) 003",
"NO. 3I/4 ADEBAYO STREET (DROVERS LANE) 004",
"BEHIND DILIMI OPP. MOSQUE (BEHIND DELIMI) 005",
"NDU STREET 006",
"COLE STREET 007",
"SARKI STREET I 008",
"SARKI STREET II 009",
"BUZU STREET I 010",
"NO. 57B BUZU STREET, OPP. MOSQUE (BUZU STREET II) 011",
"BAUCHI ROAD 012",
"NO 48 BEHIND BAUCHI RAOD (DAN MARAYA) 013",
"NO. 79/I5 BUZU STREET (SABUWAR ANGUWA) 014",
"BUTCHER LANE 015",
"DILIMI 016",
"BEHIND DILIMI 017",
"LABOUR OFFICE 018",
"LUNGUN MAKAFI 019",
"FARIN WATA 020",
"ZOLOLO JUNCTION 021",
"NO. 29/2 BAUCHI ROAD (DOGON AGOGO) 022",
"BAUCHI ROAD 023",
"LABOUR OFFICE JUNCTION 024",
"NO. I05/9 SARKI STREET (SABUWAR UNGWA) 025"],
              'JENTA ADAMU':["PLATEAU HOSPITAL JUNCTION 001",
"HILL STATION JUNCTION 002",
"UNG. MARKERI JUNCTION 003",
"PRESIDONIA J/ADAMU 004",
"NTA QTRS J/ADAMU 005",
"POLO GROUND 006",
"JENTA KASSA 007",
"ST. LUKES PRY. SCHOOL 008",
"WARDERS CLUB 009",
"HAUSA ROAD 010",
"PLATEAU HOSPITAL 011",
"NOAD ROAD 012",
"OLD BUKURU ROAD 013",
"JENTA MANGORO 014",
"UNG. JENTA MAKERI 015",
"RIYOM DRIVE 016",
"JENTA TUDUN J/ADAMU 017",
"PLATEAU HOTEL JUNCTION 018",
"PRESIDONIA J/ADAMU 019",
"ST. LUKES PRY. SCHOOL 020",
"WARDERS CLUB 021",
"PLATEAU HOSPITAL 022",
"HILL STATION JUNCTION 023",
"NTA QUARTERS J/ADAMU 024"],
              'JENTA APATA':["APATA I 001",
"APATA II 002",
"UNITY JUNCTION I003",
"UNITY JUNCTION II 004"
"MAICHIBI STREET 005",
"AFODUME STREET 006",
"OJUKWU STREET 007",
"OKPORIDO STREET 008",
"LAMBU VALLEY I 009",
"LAMBU VALLEY II 010",
"LARANTO LOOP 011",
"RAFIN PA 012",
"SDA PRY. SCHOOL 013",
"LARANTO MARKET I014",
"LARANTO MARKET II 015",
"GSS LARANTO 016",
"KATAKO BRIDGE 017",
"RAFIN PA 018",
"APATA 019",
"JENTA MIANGO 020",
"BUSA BUJI STREET 021",
"DANJA STREET 022",
"ADETUTU STREET 023",
"ZAKARIYA DIMKAT STREET 024",
"BASE SUPREME JUNCTION 025",
"TEMPEST PRY. SCHOOL 026",
"YAN TIMBA LANE 027",
"PEOPLE'S HOTEL JUNCTION 028",
"SALAMA PRIVATE SCHOOL 029",
"APATA 030",
"BUSA BUJI STREET 031",
"S.D.A PRIMARY SCHOOL 032",
"PEOPLE'S HOTEL JUNCTION 033",
"YAN TIMBER LANE 034"
], 'JOS JARAWA':["ITSITSA 001", "UNG. KAZEAZI 002", "JOS JARAWA 003", "UNG. CHIROMA 004",
"UNG. MANU AZI I 005", "UNG. MANU AZI II 006",
"LGED RIKKOS 007", "BAPTIST LAYOUT 008",
"UNG. AZI ITSE 009", "LIBERTY LAYOUT 010",
"DUTSE UKU 011","KWANGA 'B' 012",
"BAPTIST GWAFAN 013",
"NUPIS 014",
"FURAKA VILLAGE 015",
"UNG. WAKILI I 016",
"UNG. WAKILI II 017",
"KATON RIKKOS 018",
"DNCR 019",
"UNG. KAZE 020",
"UNG. NYAM BAKA 021",
"RIGUNG GWASH 022",
"YAN TRAILER 023",
"ANOTHER LIFE VILLAGE 024",
"UNG. UBAN DOMA 025",
"LAMINGO JUNCTION 026",
"LEA LAMINGO 027",
"UNG. AGIDI RIKKOS 028",
"RIKKOS CENTRE NDLEA 029",
"JOS JARAWA 030",
"PHC GWAFAN I 031",
"PHC GWAFAN II 032",
"GWASH VILLAGE 033",
"BAPTIST PRY. SCHOOL 034",
"UNG. WAKILI 035",
"UNG. CHIROMA 036",
"ROKKOS CENTRE NDLEA 037"
],
              'NARAGUTA A':["GADAN BAKO 001",
"KASUWAN DARE I 002",
"KASUWAN DARE II 003",
"NEAR MALLAM UMARU’S COMPOUND BULBULA AREA (GADAN SOGAI I) 004",
"CLOSE TO ALHAJI MOHAMMADU’S COMPOUND BULBULA (GADAN SOGAI II) 005",
"GADAN ALASARIN 006",
"NEAR A.Y.B. HASKE BREAD FILIN BALL (YAN ALIBO) 007",
"UNG. UNA 008",
"NEAR ALHAJI MALUMBO’S COMPOUND (YAMSET CLINIC) 009",
"YAN SHANU I 010",
"YAN SHANU II 011",
"UNG. AZI (FILIN BALL) 012",
"UNG. MADAKI 013",
"UNG. MADAKI 014",
"YAN SHANU III 015",
"NEAR ALHAJI SANUSI’S COMPOUND (YAN SHANU IV) 016",
"NEAR ALHAJI SULEIMAN’S COMPOUND (YAN ALIBO II) 017",
"UNG. MADAKI 018",
"BAPTIST PRY. SCHOOL 019",
"UNG. U.N.A I 020",
"UNG. U.N.A II 021",
"U.N.A AREA I 022",
"U.N.A AREA II 023",
"NEPA JUNCTION 024",
"PREMIER HOTEL JUNCTION 025",
"YAN ALIBO 026",
"FILIN BALL 027",
"CONGO JUNCTION 028",
"NEAR ALH. AZI’S COMPOUND FILIN BALL (UNG. AZI) 029",
"YAMSET CLINIC 030",
"PREMIER HOTEL JUNCTION 031",

],
              'NARAGUTA B':["KONAN SOJA 001",
"GTC JOS 002",
"UBYEL I 003",
"UBYEL II 004",
"UNG. RIMI I 005",
"UNG. RIMI II 006",
"UNG. RIMI III 007",
"KUNGA I 008",
"MAZAH TARSHI 009",
"GWONG 010",
"BEHWOL PRY. SCHOOL 011",
"MAZAH LIBA 012",
"MAZAH NAGOHOM 013",
"F.R.C. ZARIA ROAD 014",
"UNG. ROGO PRY. SCHOL 015",
"BEHIN UNIJOS I 016",
"BEHIN UNIJOS II 017",
"MALLAM CHAI 018",
"GADAN BAUCHI 019",
"UNIJOS. PRY. SCHOOL 020",
"UNG. ROGO PRY. SCHOOL I021",
"UNG. ROGO PRY. SCHOOL II 022",
"UNG. UJAH I 023",
"UNG. UJAH II 024",
"DA DUSU SQUARE 025",
"MISHKAHAM OFFICE 026",
"DA KALMA SQUARE 027",
"UNG. DA MAMMAN DANG 028",
"CHWELN YAP I 029",
"UNG. DA ADAMU ZANG 030",
"UNIV. PRY. SCHOOL I 031"
"UNIV. PRY. SCHOOL II 032"
"GOVT. STAFF QUARTERS 033",
"STUDENT VILLAGE 034",
"SABON LAYI 035",
"NARAGUTA HOSTEL 036",
"G.S.S. JOS 037",
"GIDAN SARKI FUDAWA 038",
"FUDAWA 039",
"NABOR FUDAWA 040",
"LEGISLATOR'S QUARTERS 041",
"DOGON DUTSE 042",
"MAC. WILLIAMS JUNCTION 043",
"AL‐IMAM PRY. SCHOOL 044",
"UNG. ROGO PRY. SCHOOL 045",
"G.S.S. BABALE I 046",
"TARGWONG 047",
"RAFIN JAKI 048",
"RIGIZA LEA I 049",
"RIGIZA LEA II 050",
"ZOLOLO VILLAGE SQUARE (ZOLOLO VILLAGE) 051",
"ZANGAM 052",
"YELWA 053",
"G.S.S. BABALE I 054",
"NO. 234 NASSARAWA GWONG STREET (UNG. LEKE) 055",
"UNG. RUKUBA I 056",
"UNG. RUKUBA II 057",
"UNG. RUKUBA III 058",
"AREA COURT 059",
"RUSAI VILLAGE 060",
"P.H.C UNG. ROGO 061",
"TAJIR 062",
"RUSAI VILLAGE 063",
"MAZAH YAHAM 064",
"RUSAI VILLAGE 065",
"MARAH GINZI 066",
"LEGISLATOR'S QUARTERS JUNCTION 067",
"ASIBITIN DAUDA A/ROGO I068",
"ASIBITIN DAUDA A/ROGO II 069",
"MALL. CHAI STREET 070",
"UNG. ROGO PRY. SCHOOL I071",
"UNG. ROGO PRY. SCHOOL II 072",
"NEAR ALH. IDI’S COMPOUND ANGWAN RIMI ROAD (UNG. RIMI IV) 073",
"SENIOR STAFF QUARTERS 074",
"RIZAH 075",
"UKADUM KUNGA 076",
"AYUMA UPANA 077",
"MAZAH UGITIN 078",
"YARUJE 079",
"HWOL TITHALAN 080",
"WATER WORKS 081",
"RHIKUM VILLAGE 082",
"MAZAH JUNCTION 083",
"RISHARI RHAKUBU 084",
"HWOLL NABOR VILLAGE SQUARE (ECWA SEMINARY) 085",
"KONAN MUMBUT 086",
"CHWELN YAP LGEDI 087",
"CHWELN YAP LGEDI II 088",
"YAN TRAILER 089",
"GREAT COMMISSION 090",
"UBYAL GOROH 091",
"UNG. MALLAM. CHAI 092",
"UNG. UJAH 093",
"MARKUS ISHAYA LOOP 094",
"SANI SANTI BREAD A/ROGO 095",
"DUALA HOTEL JUNCTION 096",
"KOFAR MUSA SANTANA A/ROGO 097",
"A.A. ADAM UNG. ROGO 098",
"KOFAR MAL. MUSA U/ROGO 099",
"NEPA VILLAGE ZARIA ROAD 100",
"FUDAWA 101",
"SNR. STAFF QUARTERS 102",
"GADAN BAUCHI 103",
"UNG. ROGO PRY. SCHOOL 104",
"UNG. RUKUBA 105",
"MAZAH JUNCTION 106"
],
              'SARKIN ARAB':["MOHAMMED WADA STREET 001",
"AFODUME STREET 002",
"NEW MARKET 003",
"YUSUF STREET 004",
"HALIRU STREET 005",
"ATILI STREET 006",
"MOONSHINE H. JUNCTION 007",
"SARKIN ARAB STREET 008",
"POTATOES MARKET 009",
"DODO STREET I 010",
"DODO STREET II 011",
"WILLIAM STREET 012",
"MALLAM AUDU STREET 013",
"CEMETERY STREET 014",
"AJAYI STREET 015",
"ENUGU STREET 016",
"OLD RAILWAY 017"],
                'TAFAWA BALEWA':["KASHIM IBRAHIM 001",
"PANKSHIN STREET 002",
"GOMBE AVENUE 003",
"ZIK AVENUE 004",
"TAFAWA BALEWA 005",
"TOWNSHIP SCHOOL 006",
"EYAMBA STREET 007",
"NDAGI FAROUK 008",
"NIGER AVENUE 009",
"PRESTIGE HOTEL JUNCTION 010",
"ZIK AVENUE 011"],
              'TUDUN WADA':["KABONG SOUTH 001",
"ALHERI CENTRAL 002",
"ALHERI SOUTH I 003",
"ALHERI SOUTH II 004",
"UTAN CENTRAL 005",
"ST. MURUMBA ZARIA RD I006",
"UNG. ABUJA T/WADA 007",
"UNG. LAGOS T/WADA I008",
"UNG. LAGOS T/WADA II 009",
"UNG. GADA T/WADA 010",
"UNG. MIANGO T/WADA I011",
"UNG. MIANGO T/WADA II 012",
"UNG. BAUDA T/WADA I013",
"UNG. BAUDA T/WADA II 014",
"UNG. BAUDA T/WADA III 015",
"ST. MURUMBA ZARIA RD II 016",
"UNG. WALI GADA BIYU I017",
"UNG. WALI GADA BIYU II 018",
"UNG. SOYA I 019",
"UNG. SOYA II 020",
"LEA PR. SCH. T/WADA 021",
"FED. SECRETARIAT 022",
"UNG. HAUSAWA T/WADA 023",
"APOLO CRESCENT 024",
"UNG. YASHI T/WADA I 025",
"UNG. YASHI T/WADA II 026",
"UNG. ABUJA T/WADA I 027",
"UNG. ABUJA T/WADA II 028",
"DONG VILLAGE 029",
"UNG. CHIROMA RUKUBA RD 030",
"WILD LIFE PARK 031",
"KABONG CENTRAL I032",
"KABONG CENTRAL II 033",
"KABONG RCM 034",
"UTAN NORTH 035",
"UTAN SOUTH 036",
"UNG. SARKI T/WADA 037",
"SABON GARI MADO YUDUNWADA 038",
"MADO TOURISM GATE T/WADA 039",
"ALBARKANS PRI. PRY. SCH. T/WADA 040",
"AREA COURT T/WADA 041",
"BRIGHT WAY RUKUBA ROAD 042",
"UNG. RIMI RUKUBA ROAD 043",
"UNG. CHAI KABONG 044",
"BAUDA KABONG 045",
"ALAMA JUNCTION RUKUBA RD 046",
"UNG. CHAWAI KABONG 047",
"UTAN PHC 048",
"UNG. SALE LANE U/SOYA 049",
"UNG. MATA KABONG 050",
"UNG. JUMA’A ROAD 051",
"ROCK HAVEN ZARIA RD 052",
"J.M.D.B QUARTERS, T/WADA 053",
"POST OFFICE, ZARIA ROAD 054",
"MALLAM FARI JUNCTION, ZARIA RD 055",
"GBOKO ROAD, T/WADA 056",
"DONG VILLAGE (UNG. CHIROMA) 057",
"NEPA CLOSE T/WADA 058",
"UNG. KOWA RUKUBA ROAD 059",
"BEHIND ST. MURUMBA Z/ROAD 060",
"UTAN LANE RUKUBA RD I 061",
"UNG. LAGOS T/WADA 062",
"FED. SECRETARIAT 063",
"UNG. HAUSAWA T/WADA 064",
"UTAN LANE RUKUBA RD II 065"
],
              'VANDERPUYE':["PANYAM STREET I 001",
"CHURCH STREET 002",
"SHENDAM STREET I003",
"ST. PAULS TOWNSHIP 004",
"YERWA STREET 005",
"PANYAM STREET II 006",
"RWANG PAM STREET 007",
"LANGTANG STREET 008",
"ST. THERESA BOYS SCHOOL 009",
"DOHERTY STREET 010",
"SHENDAM STREET I 011"],
}

pooling_unit={'GANGARE': ['LGED GANGARE 001', 'GSS GANGARE 002', 'ADJACENT ALHAJI MAISAJE’S HOUSE, GANGARE I (KOFAR MAISAJE I) 003', 'ADJACENT ALHAJI MAISAJE’S HOUSE, GANGARE II (KOFAR MAISAJE II) 004', 'PARENTIN ITACHE 005', 'K/ALH. GAMBO 006', 'YAN KASHI I 007', 'YAN KASHI II 008', 'K/MAL. MUSA 009', 'RICHARD WAY 010', 'POST OFFICE 011', 'RAILWAY STATION 012', 'NO. 56 MURTALA MOHAMMED WAY (MURTALA WAY) 013', 'ADJACENT ALHAJI MAGAJI HOUSE GANGARE (KOFAR MAGAJI) 014', 'ADJACENT ALHAJI SALEH HASSAN’S HOUSE GANGARE (DAKIN MINTI) 015', 'ADJACENT SARKIN DOGARIA’S HOUSE GANGARE (K/SARKIN DOGARAI) 016', 'ADJACENT SHEHU SALEH HASSAN’S COMPOUND (KOFAR SHEHU) 017', 'KOFAR YAYA 018', 'KOFAR KATAGUM 019', 'GSS GANGARE 020'],
              'JENTA\xa0ADAMU': ['PLATEAU HOSPITAL JUNCTION 001', 'HILL STATION JUNCTION 002', 'UNG. MARKERI JUNCTION 003', 'PRESIDONIA J/ADAMU 004', 'NTA QTRS J/ADAMU 005', 'POLO GROUND 006', 'JENTA KASSA 007', 'ST. LUKES PRY. SCHOOL 008', 'WARDERS CLUB 009', 'HAUSA ROAD 010', 'PLATEAU HOSPITAL 011', 'NOAD ROAD 012', 'OLD BUKURU ROAD 013', 'JENTA MANGORO 014', 'UNG. JENTA MAKERI 015', 'RIYOM DRIVE 016', 'JENTA TUDUN J/ADAMU 017', 'PLATEAU HOTEL JUNCTION 018', 'PRESIDONIA J/ADAMU 019', 'ST. LUKES PRY. SCHOOL 020', 'WARDERS CLUB 021', 'PLATEAU HOSPITAL 022', 'HILL STATION JUNCTION 023', 'NTA QUARTERS J/ADAMU 024'],
              'SARKIN\xa0ARAB': ['MOHAMMED WADA STREET 001', 'AFODUME STREET 002', 'NEW MARKET 003', 'YUSUF STREET 004', 'HALIRU STREET 005', 'ATILI STREET 006', 'MOONSHINE H. JUNCTION 007', 'SARKIN ARAB STREET 008', 'POTATOES MARKET 009', 'DODO STREET I 010', 'DODO STREET II 011', 'WILLIAM STREET 012', 'MALLAM AUDU STREET 013', 'CEMETERY STREET 014', 'AJAYI STREET 015', 'ENUGU STREET 016', 'OLD RAILWAY 017'],
              'NARAGUTA\xa0B': ['KONAN SOJA 001', 'GTC JOS 002', 'UBYEL I 003', 'UBYEL II 004', 'UNG. RIMI I 005', 'UNG. RIMI II 006', 'UNG. RIMI III 007', 'KUNGA I 008', 'MAZAH TARSHI 009', 'GWONG 010', 'BEHWOL PRY. SCHOOL 011', 'MAZAH LIBA 012', 'MAZAH NAGOHOM 013', 'F.R.C. ZARIA ROAD 014', 'UNG. ROGO PRY. SCHOL 015', 'BEHIN UNIJOS I 016', 'BEHIN UNIJOS II 017', 'MALLAM CHAI 018', 'GADAN BAUCHI 019', 'UNIJOS. PRY. SCHOOL 020', 'UNG. ROGO PRY. SCHOOL I021', 'UNG. ROGO PRY. SCHOOL II 022', 'UNG. UJAH I 023', 'UNG. UJAH II 024', 'DA DUSU SQUARE 025', 'MISHKAHAM OFFICE 026', 'DA KALMA SQUARE 027', 'UNG. DA MAMMAN DANG 028', 'CHWELN YAP I 029', 'UNG. DA ADAMU ZANG 030', 'UNIV. PRY. SCHOOL I 031UNIV. PRY. SCHOOL II 032GOVT. STAFF QUARTERS 033', 'STUDENT VILLAGE 034', 'SABON LAYI 035', 'NARAGUTA HOSTEL 036', 'G.S.S. JOS 037', 'GIDAN SARKI FUDAWA 038', 'FUDAWA 039', 'NABOR FUDAWA 040', "LEGISLATOR'S QUARTERS 041", 'DOGON DUTSE 042', 'MAC. WILLIAMS JUNCTION 043', 'AL‐IMAM PRY. SCHOOL 044', 'UNG. ROGO PRY. SCHOOL 045', 'G.S.S. BABALE I 046', 'TARGWONG 047', 'RAFIN JAKI 048', 'RIGIZA LEA I 049', 'RIGIZA LEA II 050', 'ZOLOLO VILLAGE SQUARE (ZOLOLO VILLAGE) 051', 'ZANGAM 052', 'YELWA 053', 'G.S.S. BABALE I 054', 'NO. 234 NASSARAWA GWONG STREET (UNG. LEKE) 055', 'UNG. RUKUBA I 056', 'UNG. RUKUBA II 057', 'UNG. RUKUBA III 058', 'AREA COURT 059', 'RUSAI VILLAGE 060', 'P.H.C UNG. ROGO 061', 'TAJIR 062', 'RUSAI VILLAGE 063', 'MAZAH YAHAM 064', 'RUSAI VILLAGE 065', 'MARAH GINZI 066', "LEGISLATOR'S QUARTERS JUNCTION 067", 'ASIBITIN DAUDA A/ROGO I068', 'ASIBITIN DAUDA A/ROGO II 069', 'MALL. CHAI STREET 070', 'UNG. ROGO PRY. SCHOOL I071', 'UNG. ROGO PRY. SCHOOL II 072', 'NEAR ALH. IDI’S COMPOUND ANGWAN RIMI ROAD (UNG. RIMI IV) 073', 'SENIOR STAFF QUARTERS 074', 'RIZAH 075', 'UKADUM KUNGA 076', 'AYUMA UPANA 077', 'MAZAH UGITIN 078', 'YARUJE 079', 'HWOL TITHALAN 080', 'WATER WORKS 081', 'RHIKUM VILLAGE 082', 'MAZAH JUNCTION 083', 'RISHARI RHAKUBU 084', 'HWOLL NABOR VILLAGE SQUARE (ECWA SEMINARY) 085', 'KONAN MUMBUT 086', 'CHWELN YAP LGEDI 087', 'CHWELN YAP LGEDI II 088', 'YAN TRAILER 089', 'GREAT COMMISSION 090', 'UBYAL GOROH 091', 'UNG. MALLAM. CHAI 092', 'UNG. UJAH 093', 'MARKUS ISHAYA LOOP 094', 'SANI SANTI BREAD A/ROGO 095', 'DUALA HOTEL JUNCTION 096', 'KOFAR MUSA SANTANA A/ROGO 097', 'A.A. ADAM UNG. ROGO 098', 'KOFAR MAL. MUSA U/ROGO 099', 'NEPA VILLAGE ZARIA ROAD 100', 'FUDAWA 101', 'SNR. STAFF QUARTERS 102', 'GADAN BAUCHI 103', 'UNG. ROGO PRY. SCHOOL 104', 'UNG. RUKUBA 105', 'MAZAH JUNCTION 106'],
              'JOS\xa0JARAWA': ['ITSITSA 001', 'UNG. KAZEAZI 002', 'JOS JARAWA 003', 'UNG. CHIROMA 004', 'UNG. MANU AZI I 005', 'UNG. MANU AZI II 006', 'LGED RIKKOS 007', 'BAPTIST LAYOUT 008', 'UNG. AZI ITSE 009', 'LIBERTY LAYOUT 010', 'DUTSE UKU 011', "KWANGA 'B' 012", 'BAPTIST GWAFAN 013', 'NUPIS 014', 'FURAKA VILLAGE 015', 'UNG. WAKILI I 016', 'UNG. WAKILI II 017', 'KATON RIKKOS 018', 'DNCR 019', 'UNG. KAZE 020', 'UNG. NYAM BAKA 021', 'RIGUNG GWASH 022', 'YAN TRAILER 023', 'ANOTHER LIFE VILLAGE 024', 'UNG. UBAN DOMA 025', 'LAMINGO JUNCTION 026', 'LEA LAMINGO 027', 'UNG. AGIDI RIKKOS 028', 'RIKKOS CENTRE NDLEA 029', 'JOS JARAWA 030', 'PHC GWAFAN I 031', 'PHC GWAFAN II 032', 'GWASH VILLAGE 033', 'BAPTIST PRY. SCHOOL 034', 'UNG. WAKILI 035', 'UNG. CHIROMA 036', 'ROKKOS CENTRE NDLEA 037'],
              'TUDUN\xa0WADA': ['KABONG SOUTH 001', 'ALHERI CENTRAL 002', 'ALHERI SOUTH I 003', 'ALHERI SOUTH II 004', 'UTAN CENTRAL 005', 'ST. MURUMBA ZARIA RD I006', 'UNG. ABUJA T/WADA 007', 'UNG. LAGOS T/WADA I008', 'UNG. LAGOS T/WADA II 009', 'UNG. GADA T/WADA 010', 'UNG. MIANGO T/WADA I011', 'UNG. MIANGO T/WADA II 012', 'UNG. BAUDA T/WADA I013', 'UNG. BAUDA T/WADA II 014', 'UNG. BAUDA T/WADA III 015', 'ST. MURUMBA ZARIA RD II 016', 'UNG. WALI GADA BIYU I017', 'UNG. WALI GADA BIYU II 018', 'UNG. SOYA I 019', 'UNG. SOYA II 020', 'LEA PR. SCH. T/WADA 021', 'FED. SECRETARIAT 022', 'UNG. HAUSAWA T/WADA 023', 'APOLO CRESCENT 024', 'UNG. YASHI T/WADA I 025', 'UNG. YASHI T/WADA II 026', 'UNG. ABUJA T/WADA I 027', 'UNG. ABUJA T/WADA II 028', 'DONG VILLAGE 029', 'UNG. CHIROMA RUKUBA RD 030', 'WILD LIFE PARK 031', 'KABONG CENTRAL I032', 'KABONG CENTRAL II 033', 'KABONG RCM 034', 'UTAN NORTH 035', 'UTAN SOUTH 036', 'UNG. SARKI T/WADA 037', 'SABON GARI MADO YUDUNWADA 038', 'MADO TOURISM GATE T/WADA 039', 'ALBARKANS PRI. PRY. SCH. T/WADA 040', 'AREA COURT T/WADA 041', 'BRIGHT WAY RUKUBA ROAD 042', 'UNG. RIMI RUKUBA ROAD 043', 'UNG. CHAI KABONG 044', 'BAUDA KABONG 045', 'ALAMA JUNCTION RUKUBA RD 046', 'UNG. CHAWAI KABONG 047', 'UTAN PHC 048', 'UNG. SALE LANE U/SOYA 049', 'UNG. MATA KABONG 050', 'UNG. JUMA’A ROAD 051', 'ROCK HAVEN ZARIA RD 052', 'J.M.D.B QUARTERS, T/WADA 053', 'POST OFFICE, ZARIA ROAD 054', 'MALLAM FARI JUNCTION, ZARIA RD 055', 'GBOKO ROAD, T/WADA 056', 'DONG VILLAGE (UNG. CHIROMA) 057', 'NEPA CLOSE T/WADA 058', 'UNG. KOWA RUKUBA ROAD 059', 'BEHIND ST. MURUMBA Z/ROAD 060', 'UTAN LANE RUKUBA RD I 061', 'UNG. LAGOS T/WADA 062', 'FED. SECRETARIAT 063', 'UNG. HAUSAWA T/WADA 064', 'UTAN LANE RUKUBA RD II 065'],
              'GARBA\xa0DAHO': ['SARKI STREET 001', 'GALADIMA STREET 002', 'ALH. FADI STREET I003', 'COLE STREET 004', 'PUMP STREET 005', 'BAUCHI ROAD 006', 'NDU STREET 007', 'KASUWA DARE I 008', 'KASUWA DARE II 009', 'AYENI STREET I 010', 'AYENI STREET II 011', 'BUTCHER LANE 012', 'SANI STREET 013', 'YAN TAYA 014', 'YAN TINKA 015', 'MEGA STREET 016', 'YAN DOYA 017', 'KASUWA DARE JUNCTION 018', 'SARKI STREET 019', 'YAN TAYA JUNCTION 020GALADIMA ST. JUNCTION 021', 'DILIMI STREET (BEHIND CARDINAL ROAD) 022', 'ALH. FADI STREET II 023', 'COLE STREET JUNCTION 024', 'MASSALACI DILIMI STREET 025', 'YAN KATIFA DILIMI 026'],
              'ABBA\xa0NA\xa0SHEHU': ['NO. 82/I BAUCHI ROAD (BAUCHI ROAD I) 001', 'NO. I07/I ALONG BAUCHI ROAD (BAUCHI ROAD II) 002', 'NO 64/II TURAKI LANE (YANDOKA TURAKI I) 003', 'NO 84/5 YANDOKA TURAKI LANE (YAN DOKA TURAKI) 004', 'NO. II6/I6 LAWAN NA ROGO (LAWAN NA ROGO) 005', 'NO 85/I4 YANDOKA/TURAKI (SCHOOL LANE I) 006', 'NO. III/9 SCHOOL LANE (SCHOOL LANE II) 007', 'NO. I/74/35 AUDU KENKEN (AUDU KENKEN) 008', 'NO. 68/27 MAMMAN BORNO STREET (MAMMAN BORNO I) 009', 'NO. II3/30 ALONG BUZU STREET (MAMMAN BORNO II) 010', 'NO. I25/I ABBA NA SHEHU STREET (ABBA SHEHU NA I) 011', 'NO. I28/9 ABBA NA SHEHU STREET (ABBA SHEHU NA II) 012', 'NO. I3I/3 ABBA NA SHEHU (ABBA SHEHU NA III) 013', 'NO. I32/I GARBA JIBIYA (KOFAR SARKIN KUBI) 014', 'NO. I25/II GARBA JIBIYA STREET (GARBA JIBIYA) 015', 'NO. I34/4 IDI MAI BORKONO ABBA NA (IDI MAI BORKONO) 016', 'OPPOSITE CENTRAL MOSQUE JOS (MASS JUMMA’A STREET) 017', 'AUDU LANE JUNCTION (AUDU LANE) 018', 'NO. 84/I7 TURAKI LANE (TURAKI LANE) 019', 'NO. 86/I MANGO STREET (MANGO STREET) 020', 'NO. I29/9 YAN REKE (YAN REKE) 021', 'NO. I42/3 INUWA KANO STREET (INUWA KANO) 022', 'NO. 57/2 BEHIND JOS NORTH LGC SHOPPING COMPLEX (BAKANO LANE) 023', 'NO. I2I/I3 SCHOOL LANE (SCHOOL LANE) 024', 'MATANMI HOSPITAL AND MATERNITY JOS (MAMMAN BORNO) 025', "NO. I28/I AUDU KENKEN STREET (MASSALACI JUMMA'A STREET I) 026", 'NO. I28/2 AUDU KENKEN STREET (AUDU KENKEN) 027', 'NO. I22/2 ALONG BAUCHI ROAD (BAUCHI ROAD) 028', "OPPOSITE CENTRAL MOSQUE JOS (MASSALACI JUMMA'A STREET II) 029"],
              'JENTA\xa0APATA': ['APATA I 001', 'APATA II 002', 'UNITY JUNCTION I003', 'UNITY JUNCTION II 004MAICHIBI STREET 005', 'AFODUME STREET 006', 'OJUKWU STREET 007', 'OKPORIDO STREET 008', 'LAMBU VALLEY I 009', 'LAMBU VALLEY II 010', 'LARANTO LOOP 011', 'RAFIN PA 012', 'SDA PRY. SCHOOL 013', 'LARANTO MARKET I014', 'LARANTO MARKET II 015', 'GSS LARANTO 016', 'KATAKO BRIDGE 017', 'RAFIN PA 018', 'APATA 019', 'JENTA MIANGO 020', 'BUSA BUJI STREET 021', 'DANJA STREET 022', 'ADETUTU STREET 023', 'ZAKARIYA DIMKAT STREET 024', 'BASE SUPREME JUNCTION 025', 'TEMPEST PRY. SCHOOL 026', 'YAN TIMBA LANE 027', "PEOPLE'S HOTEL JUNCTION 028", 'SALAMA PRIVATE SCHOOL 029', 'APATA 030', 'BUSA BUJI STREET 031', 'S.D.A PRIMARY SCHOOL 032', "PEOPLE'S HOTEL JUNCTION 033", 'YAN TIMBER LANE 034'],
              'IBRAHIM\xa0KATSINA': ['NO 32 ADEBAYO STREET (ADEBAYO STREET) 001', 'NO 36/IA KOLO STREET (KOLO STREET) 002', 'NO. 29/6 BAUCHI ROAD (BAUCHI ROAD) 003', 'NO. 3I/4 ADEBAYO STREET (DROVERS LANE) 004', 'BEHIND DILIMI OPP. MOSQUE (BEHIND DELIMI) 005', 'NDU STREET 006', 'COLE STREET 007', 'SARKI STREET I 008', 'SARKI STREET II 009', 'BUZU STREET I 010', 'NO. 57B BUZU STREET, OPP. MOSQUE (BUZU STREET II) 011', 'BAUCHI ROAD 012', 'NO 48 BEHIND BAUCHI RAOD (DAN MARAYA) 013', 'NO. 79/I5 BUZU STREET (SABUWAR ANGUWA) 014', 'BUTCHER LANE 015', 'DILIMI 016', 'BEHIND DILIMI 017', 'LABOUR OFFICE 018', 'LUNGUN MAKAFI 019', 'FARIN WATA 020', 'ZOLOLO JUNCTION 021', 'NO. 29/2 BAUCHI ROAD (DOGON AGOGO) 022', 'BAUCHI ROAD 023', 'LABOUR OFFICE JUNCTION 024', 'NO. I05/9 SARKI STREET (SABUWAR UNGWA) 025'],
              'TAFAWA\xa0BALEWA': ['KASHIM IBRAHIM 001', 'PANKSHIN STREET 002', 'GOMBE AVENUE 003', 'ZIK AVENUE 004', 'TAFAWA BALEWA 005', 'TOWNSHIP SCHOOL 006', 'EYAMBA STREET 007', 'NDAGI FAROUK 008', 'NIGER AVENUE 009', 'PRESTIGE HOTEL JUNCTION 010', 'ZIK AVENUE 011'], 'VANDERPUYE': ['PANYAM STREET I 001', 'CHURCH STREET 002', 'SHENDAM STREET I003', 'ST. PAULS TOWNSHIP 004', 'YERWA STREET 005', 'PANYAM STREET II 006', 'RWANG PAM STREET 007', 'LANGTANG STREET 008', 'ST. THERESA BOYS SCHOOL 009', 'DOHERTY STREET 010', 'SHENDAM STREET I 011'],
              'ALI\xa0KAZAURE': ['ABDULSALAMI ST. I001', 'NEW MARKET 002', 'NEAR THE CLAN HEAD’S COMPOUND I (KOFAR MAI UNGUWA I) 003', 'NEAR THE CLAN HEAD’S COMPOUND II (KOFAR MAI UNGUWA II) 004', 'ALH. UMAR LANE I005', 'ALH. UMAR LANE II 006', 'SARKI MANGU STREET 007', 'LAMBERT STREET 008', 'UNG. DALYOP JUNCTION I009', 'IDI MAI BORKONO 010', 'EMENIKE STREET 011', 'UNG. DALYOP JUNCTION II 012', 'HARUNA HADEJA 013', 'LASISI MAKANJUOLA 014', 'AMINGO JUNCTION I015', 'NEAR MASSALLACI IDI (KOFAR MAI UNGUWA) 016', 'MONEDO STREET 017', 'ALI KAZAURE 018', 'LGED SCHOOL 019', 'MALLAM KURE ST. 020', 'ASIBITIN KUTARE 021', 'MOSES ANYANSI ST. 022', 'NEW MARKET 023', 'COMMUNITY CENTRE 024', 'HALIRU STREET 025', 'ABDULSALAMI ST. II 026', 'ISHAKU GWAMNA ST. 027', 'NEAR MUDI NA GARBA STREET (KOFAR YAHAI MAITAYA) 028', 'FED. HOTEL JUNCTION 029', 'COMMUNITY CENTRE 030', 'RELEVANT TECH 031', 'NURUDEEN TOWNSHIP SCH. 032', 'MUDI NA GARBA 033', 'YAN KAJI 034', 'ALI KAZAURE ST. 035', 'OSUMENYI STREET 036', 'NEW MARKET 037', 'AMINGO JUNCTION II 038'],
              'NARAGUTA\xa0A': ['GADAN BAKO 001', 'KASUWAN DARE I 002', 'KASUWAN DARE II 003', 'NEAR MALLAM UMARU’S COMPOUND BULBULA AREA (GADAN SOGAI I) 004', 'CLOSE TO ALHAJI MOHAMMADU’S COMPOUND BULBULA (GADAN SOGAI II) 005', 'GADAN ALASARIN 006', 'NEAR A.Y.B. HASKE BREAD FILIN BALL (YAN ALIBO) 007', 'UNG. UNA 008', 'NEAR ALHAJI MALUMBO’S COMPOUND (YAMSET CLINIC) 009', 'YAN SHANU I 010', 'YAN SHANU II 011', 'UNG. AZI (FILIN BALL) 012', 'UNG. MADAKI 013', 'UNG. MADAKI 014', 'YAN SHANU III 015', 'NEAR ALHAJI SANUSI’S COMPOUND (YAN SHANU IV) 016', 'NEAR ALHAJI SULEIMAN’S COMPOUND (YAN ALIBO II) 017', 'UNG. MADAKI 018', 'BAPTIST PRY. SCHOOL 019', 'UNG. U.N.A I 020', 'UNG. U.N.A II 021', 'U.N.A AREA I 022', 'U.N.A AREA II 023', 'NEPA JUNCTION 024', 'PREMIER HOTEL JUNCTION 025', 'YAN ALIBO 026', 'FILIN BALL 027', 'CONGO JUNCTION 028', 'NEAR ALH. AZI’S COMPOUND FILIN BALL (UNG. AZI) 029', 'YAMSET CLINIC 030', 'PREMIER HOTEL JUNCTION 031']}


